### ISSUE TITLE
Build can't find kj

### ISSUE THREAD

**Issue by abliss** [zenhack/sandstorm-ld-preload-shim#1]
```
g++ -g -O2 -Wall -Werror -Wextra -fpermissive -std=c++14 -fPIC -MMD -I . -c -o shim.o shim.c++
shim.c++:14:10: fatal error: kj/filesystem.h: No such file or directory
 #include <kj/filesystem.h>
          ^~~~~~~~~~~~~~~~~
compilation terminated.
Makefile:48: recipe for target 'shim.o' failed
make: *** [shim.o] Error 1
```

**Comment by zenhack** [comment]
I'd been building this against the system capnproto, rather than a git checkout, maybe you don't have that installed?

...but recent work is on the `rust` branch, the C++ is going away anyway so maybe this is moot.

**Comment by abliss** [comment]
Yep, doing a `sudo make install` from capnp, and pointing the make to `/usr/local/lib`, fixed it.

**Comment by zenhack** [comment]
Cool. Closing.
